language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

cache: cargo

os:
  - linux

before_script:
  - |
      if [ $TRAVIS_RUST_VERSION = "nightly" ]; then
        cargo install rustfmt-nightly --force
      fi

matrix:
  allow_failures:
    - rust: nightly

script:
  - |
      if [ $TRAVIS_RUST_VERSION = "nightly" ]; then
        cargo fmt --all -- --write-mode=diff
      fi
  - cargo build --all --all-features
  - cargo test
  - cargo doc --all --no-deps --all-features

after_success:
  - cp ./doc_index.html ./target/doc/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "${TRAVIS_BUILD_DIR}/target/doc"
  on:
    branch: master
    rust: stable

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxldmFucyUzQXNhZmFyYWRlZy5uZXQvJTIxRkt4aGprSUNwakJWelZlQ2RGJTNBc2FmYXJhZGVnLm5ldA"
        on_success: change
        on_failure: always
        on_start: never
